<a href="https://colab.research.google.com/github/ankitranjan5/Document_Comparison/blob/main/DocumentComaprison.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
###Word2Vec

In [ ]:
import pandas as pd
import numpy as np
from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')
import re
from sklearn.feature_extraction.text import TfidfVectorizer 
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics.pairwise import euclidean_distances

# Sample corpus
documents = ['Machine learning is the study of computer algorithms that improve automatically through experience.\
Machine learning algorithms build a mathematical model based on sample data, known as training data.\
The discipline of machine learning employs various approaches to teach computers to accomplish tasks \
where no fully satisfactory algorithm is available.',
'Machine learning is closely related to computational statistics, which focuses on making predictions using computers.\
The study of mathematical optimization delivers methods, theory and application domains to the field of machine learning.',
'Machine learning involves computers discovering how they can perform tasks without being explicitly programmed to do so. \
It involves computers learning from data provided so that they carry out certain tasks.',
'Machine learning approaches are traditionally divided into three broad categories, depending on the nature of the "signal"\
or "feedback" available to the learning system: Supervised, Unsupervised and Reinforcement',
'Software engineering is the systematic application of engineering approaches to the development of software.\
Software engineering is a computing discipline.',
'A software engineer creates programs based on logic for the computer to execute. A software engineer has to be more concerned\
about the correctness of the program in all the cases. Meanwhile, a data scientist is comfortable with uncertainty and variability.\
Developing a machine learning application is more iterative and explorative process than software engineering.',
'Machine learning (ML) is a type of artificial intelligence (AI) that allows software applications to become more accurate at predicting outcomes without being explicitly programmed to do so.\
 Machine learning algorithms use historical data as input to predict new output values.',
 'Machine learning is used in internet search engines, email filters to sort out spam, websites to make personalised recommendations, banking software to detect unusual transactions, and lots of apps on our phones such as voice recognition.',
 'A software engineer is a person who applies the principles of software engineering to design, develop, maintain, test, and evaluate computer software.\
 The term programmer is sometimes used as a synonym, but may also lack connotations of engineering education or skills.',
'Software engineers may find work in large corporations, small startups, or as independent freelancers.\
 While many work in computer systems design and related services, other popular industries include finance, software publishing, and manufacturing.'
]

documents_df=pd.DataFrame(documents,columns=['documents'])

# removing special characters and stop words from the text
stop_words_l=stopwords.words('english')
documents_df['documents_cleaned']=documents_df.documents.apply(lambda x: " ".join(re.sub(r'[^a-zA-Z]',' ',w).lower() for w in x.split() if re.sub(r'[^a-zA-Z]',' ',w).lower() not in stop_words_l) )

tfidfvectoriser=TfidfVectorizer()
tfidfvectoriser.fit(documents_df.documents_cleaned)
tfidf_vectors=tfidfvectoriser.transform(documents_df.documents_cleaned)

pairwise_similarities=np.dot(tfidf_vectors,tfidf_vectors.T).toarray()
pairwise_differences=euclidean_distances(tfidf_vectors)

def most_similar(doc_id,similarity_matrix,matrix):
    print (f'Document: {documents_df.iloc[doc_id]["documents"]}')
    print ('\n')
    print ('Similar Documents:')
    if matrix=='Cosine Similarity':
        similar_ix=np.argsort(similarity_matrix[doc_id])[::-1]
        print(similar_ix)
        print(similarity_matrix)
    elif matrix=='Euclidean Distance':
        similar_ix=np.argsort(similarity_matrix[doc_id])
    for ix in similar_ix:
        if ix==doc_id:
            continue
        print('\n')
        print (f'Document: {documents_df.iloc[ix]["documents"]}')
        print (f'{matrix} : {similarity_matrix[doc_id][ix]}')

most_similar(0,pairwise_similarities,'Cosine Similarity')
#most_similar(0,pairwise_differences,'Euclidean Distance') 

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
Document: Machine learning is the study of computer algorithms that improve automatically through experience.Machine learning algorithms build a mathematical model based on sample data, known as training data.The discipline of machine learning employs various approaches to teach computers to accomplish tasks where no fully satisfactory algorithm is available.


Similar Documents:
[0 2 1 6 3 5 4 7 8 9]
[[1.         0.23203896 0.23343698 0.15232012 0.06557998 0.12363556
  0.19012604 0.05567574 0.01611037 0.01590609]
 [0.23203896 1.         0.13498101 0.08082684 0.03613263 0.06827683
  0.08881727 0.04716847 0.         0.03340937]
 [0.23343698 0.13498101 1.         0.067858   0.         0.05261303
  0.22375636 0.03564017 0.         0.        ]
 [0.15232012 0.08082684 0.067858   1.         0.03871145 0.03467997
  0.07136719 0.0379012  0.         0.        ]
 [0.06557998 0.03613263 

In [ ]:
tfidf_vectors=tfidf_vectors.toarray()

In [ ]:
pairwise = cosine_similarity(tfidf_vectors)
most_similar(0,pairwise,'Cosine Similarity')


Document: Machine learning is the study of computer algorithms that improve automatically through experience.Machine learning algorithms build a mathematical model based on sample data, known as training data.The discipline of machine learning employs various approaches to teach computers to accomplish tasks where no fully satisfactory algorithm is available.


Similar Documents:
[0 2 1 6 3 5 4 7 8 9]
[[1.         0.23203896 0.23343698 0.15232012 0.06557998 0.12363556
  0.19012604 0.05567574 0.01611037 0.01590609]
 [0.23203896 1.         0.13498101 0.08082684 0.03613263 0.06827683
  0.08881727 0.04716847 0.         0.03340937]
 [0.23343698 0.13498101 1.         0.067858   0.         0.05261303
  0.22375636 0.03564017 0.         0.        ]
 [0.15232012 0.08082684 0.067858   1.         0.03871145 0.03467997
  0.07136719 0.0379012  0.         0.        ]
 [0.06557998 0.03613263 0.         0.03871145 1.         0.26941643
  0.049866   0.05296498 0.34176593 0.09868251]
 [0.12363556 0.06827

In [ ]:
documents_df

documents                                  documents_cleaned
0  Machine learning is the study of computer algo...  machine learning study computer algorithms imp...
1  Machine learning is closely related to computa...  machine learning closely related computational...
2  Machine learning involves computers discoverin...  machine learning involves computers discoverin...
3  Machine learning approaches are traditionally ...  machine learning approaches traditionally divi...
4  Software engineering is the systematic applica...  software engineering systematic application en...
5  A software engineer creates programs based on ...  software engineer creates programs based logic...
6  Machine learning (ML) is a type of artificial ...  machine learning  ml  type artificial intellig...
7  Machine learning is used in internet search en...  machine learning used internet search engines ...
8  A software engineer is a person who applies th...  software engineer person applies principles so...
9  Software engineers may find work in large corp...  software engineers may find work large corpora...

In [ ]:
print(tfidf_vectors.shape)

(10, 166)


In [ ]:
tfidfvectoriser

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=1.0, max_features=None,
                min_df=1, ngram_range=(1, 1), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words=None, strip_accents=None,
                sublinear_tf=False, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, use_idf=True, vocabulary=None)

In [ ]:
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
tokenizer=Tokenizer()
tokenizer.fit_on_texts(documents_df.documents_cleaned)
tokenized_documents=tokenizer.texts_to_sequences(documents_df.documents_cleaned)
tokenized_paded_documents=pad_sequences(tokenized_documents,maxlen=64,padding='post')
vocab_size=len(tokenizer.word_index)+1
print (tokenized_paded_documents[0])

[ 3  1 13  6  8 29 30 31  3  1  8 32 14 33 15 34  5 35 36  5 16 17  3  1
 37 38  9 39  7 40 10 41 42 43 18  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]


In [ ]:
print(len(tokenizer.word_index))

166


In [ ]:
np.shape(tokenized_paded_documents)
#len(tokenized_paded_documents[0])

(10, 64)

In [ ]:
import gensim
W2V_PATH="https://s3.amazonaws.com/dl4j-distribution/GoogleNews-vectors-negative300.bin.gz"
model_w2v = gensim.models.KeyedVectors.load_word2vec_format(W2V_PATH, binary=True)

In [ ]:
embedding_matrix=np.zeros((vocab_size,300))
for word,i in tokenizer.word_index.items():
    if word in model_w2v:
        embedding_matrix[i]=model_w2v[word]
# creating document-word embeddings
document_word_embeddings=np.zeros((len(tokenized_paded_documents),64,300))
for i in range(len(tokenized_paded_documents)):
    for j in range(len(tokenized_paded_documents[0])):
        document_word_embeddings[i][j]=embedding_matrix[tokenized_paded_documents[i][j]]
document_word_embeddings.shape

(10, 64, 300)

In [ ]:
print(embedding_matrix)  # For 10 examples, all padded to a length of 64, and all tokens represented as a vector of dimension 300

[[ 0.          0.          0.         ...  0.          0.
   0.        ]
 [-0.08837891  0.1484375  -0.06298828 ...  0.02026367  0.11621094
   0.17578125]
 [ 0.20410156 -0.30078125 -0.01391602 ... -0.0144043  -0.03735352
   0.10742188]
 ...
 [ 0.07373047  0.0625      0.00765991 ...  0.00656128  0.11962891
   0.03515625]
 [ 0.12597656 -0.13867188 -0.38671875 ...  0.32226562 -0.06347656
   0.2109375 ]
 [ 0.04516602 -0.01318359  0.05932617 ...  0.046875    0.13867188
  -0.2109375 ]]


In [ ]:
print(len(model_w2v.vocab))

3000000


In [ ]:
document_embeddings=np.zeros((len(tokenized_paded_documents),300))
words=tfidfvectoriser.get_feature_names()
for i in range(len(document_word_embeddings)):
    for j in range(len(words)):
    #for j in range(6):
        document_embeddings[i]+=embedding_matrix[tokenizer.word_index[words[j]]]*tfidf_vectors[i][j]
        #document_embeddings[i] += embedding_matrix[tokenizer.word_index[words[j]]]
        #print(words[j])
document_embeddings = document_embeddings/64.0        
print (document_embeddings.shape)
pairwise_similarities=cosine_similarity(document_embeddings)
pairwise_differences=euclidean_distances(document_embeddings)
most_similar(0,pairwise_similarities,'Cosine Similarity')
most_similar(0,pairwise_differences,'Euclidean Distance')

(10, 300)
Document: Machine learning is the study of computer algorithms that improve automatically through experience.Machine learning algorithms build a mathematical model based on sample data, known as training data.The discipline of machine learning employs various approaches to teach computers to accomplish tasks where no fully satisfactory algorithm is available.


Similar Documents:
[0 1 6 5 2 8 3 7 4 9]
[[1.         0.84291781 0.75642608 0.69121715 0.63534575 0.77543753
  0.82027802 0.65298063 0.74850142 0.61404478]
 [0.84291781 1.         0.68370666 0.58329247 0.66692227 0.75804054
  0.78353561 0.618504   0.69947622 0.58503674]
 [0.75642608 0.68370666 1.         0.64090677 0.47321209 0.63795546
  0.6864958  0.5995911  0.63688933 0.5689121 ]
 [0.69121715 0.58329247 0.64090677 1.         0.43587498 0.57723619
  0.69412754 0.55027112 0.61661155 0.52603177]
 [0.63534575 0.66692227 0.47321209 0.43587498 1.         0.79077183
  0.54491744 0.49017674 0.74308354 0.66579411]
 [0.775437

In [ ]:
print(len(words))
print(tfidf_vectors[5][0].shape)

166
()


In [ ]:
pip install sentence_transformers

In [ ]:
from sentence_transformers import SentenceTransformer
sbert_model = SentenceTransformer('bert-base-nli-mean-tokens')
roberta_model = SentenceTransformer('sentence-transformers/roberta-large-nli-stsb-mean-tokens')

document_embeddings = sbert_model.encode(documents_df['documents_cleaned'])


pairwise_similarities=cosine_similarity(document_embeddings)
pairwise_differences=euclidean_distances(document_embeddings)

most_similar(0,pairwise_similarities,'Cosine Similarity')
most_similar(0,pairwise_differences,'Euclidean Distance')

Document: Machine learning is the study of computer algorithms that improve automatically through experience.Machine learning algorithms build a mathematical model based on sample data, known as training data.The discipline of machine learning employs various approaches to teach computers to accomplish tasks where no fully satisfactory algorithm is available.


Similar Documents:
[0 1 5 6 4 8 2 7 9 3]
[[1.0000002  0.8365411  0.61181056 0.4764781  0.6589278  0.8159458
  0.6739427  0.5920265  0.65272367 0.5633101 ]
 [0.8365411  1.0000002  0.67819023 0.5372205  0.7253679  0.7829639
  0.7030667  0.594384   0.6784701  0.5714769 ]
 [0.61181056 0.67819023 1.0000001  0.6800261  0.6249758  0.71018076
  0.78375816 0.5482248  0.78433067 0.52926284]
 [0.4764781  0.5372205  0.6800261  1.0000001  0.5375691  0.62298465
  0.60543746 0.41158336 0.6364434  0.36151946]
 [0.6589278  0.7253679  0.6249758  0.5375691  1.0000002  0.78826344
  0.60478365 0.43487012 0.76580393 0.54486525]
 [0.8159458  0.7829639

In [ ]:
document_embeddings

array([[-0.6462996 ,  0.46982914,  1.0278946 , ..., -0.6591634 ,
        -1.0581813 ,  0.8507307 ],
       [-0.9836601 ,  0.38606933,  0.50042105, ..., -1.0048016 ,
        -1.4149024 ,  1.1442695 ],
       [ 0.03516449,  0.5242567 ,  0.27247146, ..., -0.31340265,
        -1.5459914 ,  0.76212037],
       ...,
       [ 0.11838251,  1.5302067 ,  0.6174165 , ..., -0.6504145 ,
        -0.92233795,  0.9099771 ],
       [ 0.5743936 ,  0.6525071 ,  0.81171215, ..., -0.5355722 ,
        -1.3866793 ,  0.3457433 ],
       [ 0.26488706,  1.1823378 , -0.18082766, ..., -0.7829871 ,
        -0.88077295, -0.08751458]], dtype=float32)

In [ ]:
document_embeddings.shape

(10, 768)

In [ ]:
document_embedding_mpnet = np.zeros((6,384))
mp_net = SentenceTransformer('sentence-transformers/all-mpnet-base-v2')

Downloading:   0%|          | 0.00/1.18k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/10.1k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/571 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/116 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/39.3k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/349 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/438M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/239 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/466k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/363 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/13.1k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/232k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [ ]:
document_embedding_mpnet = mp_net.encode(documents_df['documents_cleaned'])

In [ ]:
print(document_embedding_mpnet.shape)

(10, 768)


In [ ]:
pairwise_similarities=cosine_similarity(document_embedding_mpnet)
pairwise_differences=euclidean_distances(document_embedding_mpnet)


In [ ]:
most_similar(0,pairwise_similarities,'Cosine Similarity')
most_similar(0,pairwise_differences,'Euclidean Distance')

Document: Machine learning is the study of computer algorithms that improve automatically through experience.Machine learning algorithms build a mathematical model based on sample data, known as training data.The discipline of machine learning employs various approaches to teach computers to accomplish tasks where no fully satisfactory algorithm is available.


Similar Documents:
[0 1 2 6 3 5 7 4 8 9]
[[1.0000001  0.73319507 0.6964721  0.67590666 0.39955193 0.5378081
  0.6761082  0.49952602 0.33269238 0.1919399 ]
 [0.73319507 1.         0.55672276 0.53478825 0.29086578 0.45203748
  0.56550705 0.39656967 0.20156035 0.14093328]
 [0.6964721  0.55672276 0.99999994 0.5507376  0.25432637 0.4693631
  0.64655936 0.39086908 0.3009907  0.13746817]
 [0.67590666 0.53478825 0.5507376  1.0000004  0.2925002  0.29214188
  0.5631695  0.40483153 0.19516903 0.11092412]
 [0.39955193 0.29086578 0.25432637 0.2925002  0.99999976 0.6492091
  0.39896736 0.21457112 0.49636707 0.4567935 ]
 [0.5378081  0.45203748

In [ ]:
document_embeddings_roberta = roberta_model.encode(documents_df['documents_cleaned'])

In [ ]:
pairwise_similarities_roberta =cosine_similarity(document_embeddings_roberta)
pairwise_differences_roberta =euclidean_distances(document_embeddings_roberta)

most_similar(0,pairwise_similarities_roberta,'Cosine Similarity')
most_similar(0,pairwise_differences_roberta,'Euclidean Distance')

Document: Machine learning is the study of computer algorithms that improve automatically through experience.Machine learning algorithms build a mathematical model based on sample data, known as training data.The discipline of machine learning employs various approaches to teach computers to accomplish tasks where no fully satisfactory algorithm is available.


Similar Documents:
[0 1 2 6 3 5 8 4 7 9]
[[1.         0.81079173 0.7320616  0.63351524 0.5499431  0.6256152
  0.66038465 0.43905246 0.56921136 0.38162953]
 [0.81079173 1.         0.58235437 0.5535016  0.52407074 0.571111
  0.67210436 0.38909295 0.48218006 0.35244375]
 [0.7320616  0.58235437 0.99999994 0.60779923 0.3837179  0.5058363
  0.7196865  0.43478796 0.49536437 0.32771876]
 [0.63351524 0.5535016  0.60779923 1.0000002  0.3557558  0.42611918
  0.57954234 0.35814014 0.3596986  0.27657807]
 [0.5499431  0.52407074 0.3837179  0.3557558  1.0000005  0.62712127
  0.30565327 0.28267103 0.75275654 0.42573142]
 [0.6256152  0.571111   